TodoListApp.WebApp/Controllers/TodoListController.cs
#pragma warning disable SA1200

using Microsoft.AspNetCore.Mvc;
using TodoListApp.Services.WebApi;
using Microsoft.AspNetCore.Identity;

namespace TodoListApp.WebApp.Controllers
{
    public class TodoListController : Controller
    {
        private readonly TodoListWebApiService _todoListService;
        private readonly TodoTaskWebApiService _todoTaskService;
        private readonly UserManager<IdentityUser> _userManager;

        public TodoListController(TodoListWebApiService todoListService, TodoTaskWebApiService todoTaskService, UserManager<IdentityUser> userManager)
        {
            _todoListService = todoListService;
            _todoTaskService = todoTaskService;
            _userManager = userManager;

        }

        public async Task<IActionResult> Index()
        {
            var todoLists = await _todoListService.GetTodoListsAsync();
            var viewModelLists = todoLists.Select(t => new TodoListApp.Services.Models.TodoList
            {
                Id = t.Id,
                Name = t.Name,
                UserId = t.UserId

                // Map other properties as needed
            });
            var returnList = new List<TodoListApp.Services.Models.TodoList>();
            foreach (var list in viewModelLists)
            {
                var newObject = new TodoListApp.Services.Models.TodoList
                {
                    Id = list.Id,
                    Name = list.Name,
                    UserId = list.UserId,
                    // Add additional properties here
                    Tasks = await _todoTaskService.GetTasksAsync(list.Id),
                };

                returnList.Add(newObject);
            }

            return View(returnList);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(TodoListApp.Services.Models.TodoList todoList)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user != null)
            {
                if (ModelState.IsValid)
                {
                    Guid userIdGuid;

                    if (Guid.TryParse(user.Id, out userIdGuid))
                    {
                        todoList.UserId = userIdGuid;
                    }
                    await _todoListService.AddTodoListAsync(todoList);
                    return RedirectToAction(nameof(Index));
                }
            }
            if (ModelState.IsValid)
            {
                await _todoListService.AddTodoListAsync(todoList);
                return RedirectToAction(nameof(Index));
            }
            return View(todoList);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> Delete(Guid todoListId)
        {
            await _todoListService.DeleteTodoListAsync(todoListId);
            return Redirect(Request.Headers["Referer"].ToString());
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var todoList = await _todoListService.GetTodoListAsync(id);
            if (todoList == null)
            {
                return NotFound();
            }

            return View(todoList);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(TodoListApp.Services.Models.TodoList todoList)
        {
            await _todoListService.UpdateTodoListAsync(todoList);
            return RedirectToAction(nameof(Index));
        }


    }
}

TodoListApp.WebApp/Controllers/TodoTaskController.cs
#pragma warning disable SA1200

using Microsoft.AspNetCore.Mvc;

using TodoListApp.Services.Models; // Ensure this matches the namespace of your TodoTask model

namespace TodoListApp.WebApp.Controllers
{
    public class TodoTaskController : Controller
    {
        private readonly TodoTaskWebApiService _todoTaskService;

        public TodoTaskController(TodoTaskWebApiService todoTaskService)
        {
            _todoTaskService = todoTaskService;
        }

        public async Task<IActionResult> Index(Guid todoListId)
        {
            var tasks = await _todoTaskService.GetTasksAsync(todoListId);
            return View(tasks); // Assumes you have an Index view for listing tasks
        }

        public async Task<IActionResult> Details(Guid todoListId, Guid taskId)
        {
            try
            {
                var task = await _todoTaskService.GetTaskAsync(todoListId, taskId);
                if (task == null)
                {
                    // Log the event or handle it as needed
                    return NotFound($"Task with ID {taskId} in TodoList with ID {todoListId} was not found.");
                }

                return View(task); // Passes the task to the Details view
            }
            catch (HttpRequestException ex) when (ex.StatusCode == System.Net.HttpStatusCode.NotFound)
            {
                // Log the error or handle it as needed
                return NotFound($"Task with ID {taskId} in TodoList with ID {todoListId} was not found.");
            }
            catch (Exception ex)
            {
                // Log the error or handle it as needed
                return StatusCode(500, "An error occurred while processing your request.");
            }
        }

        public IActionResult Create(Guid todoListId)
        {
            return View(new TodoTask { TodoListId = todoListId }); // Pass a new task model to your Create view
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Guid todoListId, TodoTask task)
        {

            if (ModelState.IsValid)
            {

                await _todoTaskService.AddTaskAsync(todoListId, task);

                return RedirectToAction(nameof(Index), new { todoListId });
            }
            return View(task);
        }

        // GET: TodoTask/Delete/5
        public async Task<IActionResult> Delete(Guid? todoListId, Guid? taskId)
        {
            if (todoListId == null || taskId == null)
            {
                return NotFound();
            }

            var task = await _todoTaskService.GetTaskAsync(todoListId.Value, taskId.Value);
            if (task == null)
            {
                return NotFound();
            }

            return View(task); // Show a view that asks the user to confirm the deletion
        }

        [HttpPost, ActionName("DeleteConfirmed")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid todoListId, Guid taskId)
        {
            await _todoTaskService.DeleteTaskAsync(todoListId, taskId);
            return Redirect(Request.Headers["Referer"].ToString());
        }


        // GET: TodoTask/Edit/5
        public async Task<IActionResult> Edit(Guid todoListId, Guid taskId)
        {
            try
            {
                var task = await _todoTaskService.GetTaskAsync(todoListId, taskId);
                if (task == null)
                {
                    return NotFound($"Task with ID {taskId} in TodoList with ID {todoListId} was not found.");
                }

                return View(task); // Passes the task to the Edit view
            }
            catch (HttpRequestException ex) when (ex.StatusCode == System.Net.HttpStatusCode.NotFound)
            {
                // Log the error or handle it as needed
                return NotFound($"Task with ID {taskId} in TodoList with ID {todoListId} was not found.");
            }
            catch (Exception ex)
            {
                // Log the error or handle it as needed
                return StatusCode(500, "An error occurred while processing your request.");
            }
        }

        // POST: TodoTask/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid todoListId, TodoTask task)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await _todoTaskService.UpdateTaskAsync(todoListId, task);
                    return RedirectToAction(nameof(Details), new { todoListId, taskId = task.Id });
                }
                catch (HttpRequestException ex)
                {
                    // Log the error or handle it as needed
                    ModelState.AddModelError("", "Error occurred while trying to update the task.");
                }
                catch (Exception ex)
                {
                    // Log the error or handle it as needed
                    return StatusCode(500, "An error occurred while processing your request.");
                }
            }

            return View(task);
        }
    }
}

TodoListApp.WebApp/Views/TodoList/Create.cshtml
@model TodoListApp.Services.Models.TodoList

@{
    ViewData["Title"] = "Add New Todo List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewData["Title"]</h2>

<div class="container mt-3">
    <form asp-action="Create" method="post">
        <div class="form-group">
            <label asp-for="Name" class="control-label">Name</label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-primary">Create</button>
        </div>
    </form>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

TodoListApp.WebApp/Views/TodoList/Edit.cshtml
@model TodoListApp.Services.Models.TodoList

<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h2>Edit To-do List</h2>
            <form asp-action="Edit" method="post">
                <input type="hidden" asp-for="Id" />

                <div class="form-group">
                    <label asp-for="Name"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>

                <button type="submit" class="btn btn-primary">Update To-do List</button>
            </form>
        </div>
    </div>
</div>

TodoListApp.WebApp/Views/TodoList/Index.cshtml
@model IEnumerable<TodoListApp.Services.Models.TodoList>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container mt-5">
    
    <nav class="mb-4 navbar navbar-light bg-light d-flex justify-content-between align-items-center">
        <a class="navbar-brand" href="#">Todo lists</a>
        <button id="addTaskBtn" class="btn btn-primary" onclick="location.href='@Url.Action("Create", "TodoList")'">Add New List</button>

    </nav>
    <div class="row">
            @foreach (var list in Model)
            {
            
            <div class=" col-md-4">
            <div class="card" style="width: 18rem;">
                <div class="card-header d-flex align-items-center justify-content-between">
                        <div id="@($"{list.Id}name")">
                            <button type="button" class="btn btn-info btn-sm" onclick="location.href='@Url.Action("Edit", "TodoList", new {Id = list.Id})'">
                                <svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="25" height="25" viewBox="0 0 64 64">
                                    <path d="M39.086 17.914l7 7L21.505 49.495l-9.201 4.412c-1.367.457-2.668-.844-2.211-2.211l4.412-9.201L39.086 17.914zM41.914 15.086l4.5-4.5c.781-.781 2.047-.781 2.828 0l4.172 4.172c.781.781.781 2.047 0 2.828l-4.5 4.5L41.914 15.086z"></path>
                                </svg>
                            </button>
                           
                            <button onclick="confirmDelete2('@list.Id')" class="btn btn-small text-white">
                                <svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="48" height="35" viewBox="0,0,256,256"
                                     style="fill:#000000;">
                                    <g transform="translate(49.92,49.92) scale(0.61,0.61)"><g fill="#dddddd" fill-rule="nonzero" stroke="none" stroke-width="1" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="10" stroke-dasharray="" stroke-dashoffset="0" font-family="none" font-weight="none" font-size="none" text-anchor="none" style="mix-blend-mode: normal"><path d="M-81.83607,337.83607v-419.67213h419.67213v419.67213z" id="bgRectangle"></path></g><g fill="#fa5252" fill-rule="nonzero" stroke="none" stroke-width="1" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="10" stroke-dasharray="" stroke-dashoffset="0" font-family="none" font-weight="none" font-size="none" text-anchor="none" style="mix-blend-mode: normal"><path d="M-29.37705,337.83607c-28.97231,0 -52.45902,-23.4867 -52.45902,-52.45902v-314.7541c0,-28.97231 23.4867,-52.45902 52.45902,-52.45902h314.7541c28.97231,0 52.45902,23.4867 52.45902,52.45902v314.7541c0,28.97231 -23.4867,52.45902 -52.45902,52.45902z" id="shape"></path></g><g fill="#000000" fill-rule="nonzero" stroke="none" stroke-width="1" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="10" stroke-dasharray="" stroke-dashoffset="0" font-family="none" font-weight="none" font-size="none" text-anchor="none" style="mix-blend-mode: normal"><g transform="scale(3.55556,3.55556)"><path d="M32,13c-1.105,0 -2,0.895 -2,2v1h-13c-2.209,0 -4,1.791 -4,4c0,1.97365 1.43236,3.60263 3.3125,3.92969l2.39453,28.73437c0.346,4.147 3.81361,7.33594 7.97461,7.33594h18.63672c4.161,0 7.62761,-3.18894 7.97461,-7.33594l2.39453,-28.73437c1.88014,-0.32705 3.3125,-1.95604 3.3125,-3.92969c0,-2.209 -1.791,-4 -4,-4h-13v-1c0,-1.105 -0.895,-2 -2,-2zM24.34766,24h23.30469l-2.25586,27.08203c-0.044,0.518 -0.47805,0.91797 -0.99805,0.91797h-16.79688c-0.52,0 -0.95409,-0.39997 -0.99609,-0.91797z"></path></g></g></g>
                                </svg>
                                
                            </button>
                           
                          <span> @list.Name</span>
                        </div>
                        <a href="https://localhost:7163/TodoTask?todoListId=@list.Id">
                            <svg width="30px" height="30px" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" fill="#000000">
                                <!-- Pencil Body -->
                                <path d="M0 21.5l2-2 2 2h16v2h-20v-2zm23.5-20c-.1 0-.3.1-.4.3l-13 13-2.6 7.8c-.1.4.4.8.7.7l7.8-2.6 13-13c.2-.2.3-.3.3-.4v-4.8h-4.8zm-4.9 3.9l-9.2 9.2-1.4 4.3 4.3-1.4 9.2-9.2-2.9-2.9z" />
                                <!-- Pencil Tip -->
                                <path d="M3 19.5l5 5-2.5 0.8-2.3-2.3z" />
                            </svg>
                        </a>
                </div>
                    <ul class="list-group list-group-flush">
                        @foreach (var task in list.Tasks)
                        {

                            <li class="list-group-item d-flex align-items-center justify-content-between">
                                <div class="d-flex align-items-center">
                                    <!-- Task icon based on active/inactive status -->
                                    <i class="bi me-2 bi-check-circle-fill text-success"></i>
                                    <a>
                                        @task.Title
                                    </a>
                                </div>
                                <button onclick="confirmDelete('@task.TodoListId', '@task.Id')"  class="btn btn-small text-white bg-danger">remove</button>

                            </li>
                        }
                      
                       
                    </ul>
                   
            </div>
            </div>
                <!-- Add more details as needed -->
            }
       
        <!-- Add more todos as needed -->
    <!-- Add more rows for additional todos -->
</div>
<script >
    function showEdit(id) {
            if (document.getElementById(`${id}form`).classList.contains('d-none')) {
                    document.getElementById(`${id}form`).classList.remove('d-none');
                    document.getElementById(`${id}form`).classList.add('d-block');
                    document.getElementById(`${id}name`).classList.add('d-none');
                    document.getElementById(`${id}name`).classList.remove('d-block');
            } else {
                document.getElementById(`${id}form`).classList.add('d-none');
                document.getElementById(`${id}form`).classList.remove('d-block');
                document.getElementById(`${id}name`).classList.remove('d-none');
                document.getElementById(`${id}name`).classList.add('d-block');
               
            }
        }

        function confirmDelete(todoListId, taskId) {
            if (confirm("Are you sure you want to delete this task?")) {
                var form = document.createElement('form');
                document.body.appendChild(form);
                form.method = 'post';
                form.action = '@Url.Action("DeleteConfirmed", "TodoTask")';
                var input = document.createElement('input');
                input.type = 'hidden';
                input.name = 'taskId';
                input.value = taskId;
                form.appendChild(input);
                var input2 = document.createElement('input');
                input2.type = 'hidden';
                input2.name = 'todoListId';
                input2.value = todoListId;
                form.appendChild(input2);
                var token = '@Html.AntiForgeryToken()';
                form.appendChild($(token)[0]);
                form.submit();
            }
        }

        function confirmDelete2(todoListId) {
            if (confirm("Are you sure you want to delete this task?")) {
                var form = document.createElement('form');
                document.body.appendChild(form);
                form.method = 'post';
                form.action = '@Url.Action("Delete", "TodoList")';
                var input2 = document.createElement('input');
                input2.type = 'hidden';
                input2.name = 'todoListId';
                input2.value = todoListId;
                form.appendChild(input2);
                var token = '@Html.AntiForgeryToken()';
                form.appendChild($(token)[0]);
                form.submit();
            }
        }
</script>
<!-- Display to-do lists here -->